import './globals.css';
import { Syne } from 'next/font/google';

const syne = Syne({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Thomas Gosset-Bazin — Designer & developer',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={syne.className}>
        <div>
          <nav>+</nav>
          <main className="grid h-screen grid-cols-1 md:grid-cols-[1fr_auto_1fr]">
            <div className="hidden md:block"></div>
            {children}
            <div className="hidden md:block"></div>
          </main>
          <footer></footer>
        </div>
      </body>
    </html>
  )
}
